# Site settings
title: "mz's blog"
email: daniel_pub@hotmail.com
description: "Memory is not reliable."
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: rdiscount
rdiscount:
 extensions: [smart]
permalink: /articles/:title
paginate: 3